### ISSUE TITLE
not able to install

### ISSUE THREAD

**Issue by lain6631** [danielfrg/word2vec#1]
I tried the windows installer and the pip method to try to install it, on both python 3.3 and python 2.7 it gave me errors. For the windows explorer it said no python directory was found, and with the pip method on both 3.3 and 2.7 it gave me Windows Error:[Error 2] with information of the 'subprocess.call' function failing to find a file. My system is windows 7, tried on both 32bits and 64bits.

**Comment by zhuchiheng** [comment]
I get the same issue when tried to install word2vec...
My environment:  Win7_64bit + anaconda 2.2.0(python2.7)

-------------------logs as follow--------------------
C:\Users\xxx\Documents\workspace\tools\word2vec\word2vec-0.7.1>python
 setup.py install
gcc word2vec-c\word2vec.c -o bin\word2vec -lm -pthread -O3 -Wall -march=native -
funroll-loops -Wno-unused-result
Traceback (most recent call last):
  File "setup.py", line 35, in <module>
    compile('word2vec.c', 'word2vec')
  File "setup.py", line 30, in compile
    return_code = subprocess.call(command)
  File "C:\Anaconda\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Anaconda\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Anaconda\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2]
-----------------------logs end--------------------

**Comment by danielfrg** [comment]
Thanks for the reports, this is a know issue: https://github.com/danielfrg/word2vec/issues/12 

Unfortunately i don't have a windows box or vm where i can possibly test this.
