### ISSUE TITLE
word2phrase

### ISSUE THREAD

**Issue by dineshbvadhia** [danielfrg/word2vec#10]
Is there an example on how to use word2phrase - preferably from within a python script? Btw, I use Anaconda.

**Comment by danielfrg** [comment]
There is not one right now but it should be simple to figure it out based on the [function declaration](https://github.com/danielfrg/word2vec/blob/master/word2vec/scripts_interface.py#L107-L122) and the [existing example](http://nbviewer.ipython.org/github/danielfrg/word2vec/blob/master/examples/word2vec.ipynb). So something like:

```
import word2vec
word2vec.word2phrase('input', 'output')
```

**Comment by dineshbvadhia** [comment]
ok. will have a go.

**Comment by dineshbvadhia** [comment]
Having some problems getting word2phrase to work. I've assumed that word2phrase is what others call phrase2vec, paragraph2vec or doc2vec - is that correct?

If so, what is the input file into word2vec.word2phrase('input', 'output')? If it is the sentences file then does the function create a vocabularly followed by the word vectors before the sentence vectors?

Trying to understand the process. Thanks!

**Comment by danielfrg** [comment]
No, I think you already found out that `word2phrase` is not `doc2vec`.

The output of `word2phrase` is a text file that then you can use as input to `word2vec`.

The output of `word2vec` will have a modified version of the input text and it will merge "phrases" (ngrams) like "Los Angeles" to "Los_Angeles".

**Comment by danielfrg** [comment]
I added `word2phrase` to the example notebook in https://github.com/danielfrg/word2vec/commit/51207081fcee8327b2f3e9d8ba6b6ec405209dee.

There was a bug in the command call but it should be fixed now.

I am closing this now but feel free to ask any other questions :)
