### ISSUE TITLE
new word2vec.c dated jan 30, 2015

### ISSUE THREAD

**Issue by dineshbvadhia** [danielfrg/word2vec#11]
just in case, there is a newer word2vec.c dated jan 30, 2015 - 
https://code.google.com/p/word2vec/source/browse/#svn%2Ftrunk

**Comment by danielfrg** [comment]
https://github.com/danielfrg/word2vec/commit/6530fb7d5448430050eb329e5e2c2b902b74bdd5 Adds the latest word2vec source.
