### ISSUE TITLE
it seems that word2vec-doc2vec does not work yet

### ISSUE THREAD

**Issue by hiyijian** [danielfrg/word2vec#17]
I used following command to train doc vector:
word2vec-doc2vec -train ../data/paper.seg -output ../data/model/paper.vec.bin -size 100 -window 5 -alpha 0.025 -sample 1e-3 -hs 0 -negative 5 -min-count 5 -cbow 1 -threads 4 -iter 20 -sentence-vectors 1 -binary 1
the train file looks like this:
_\*2599671 公路 工程造价 管理信息系统
_\*2599672 湖南 电视产业 电视台 管理体制改革 集团化 网络建设 竞争机制
_\*2599673 超高功率电弧炉 强化用氧技术 最佳氧耗值 电炉炼钢 南京钢铁集团有限公司 脱碳 氧气 节能
_\*2599674 retran程序 乏燃料贮存水池 热工水力安全分析 核电厂安全 点池模型
_\*2599675 北方地区 住宅建筑 电采暖 用电负荷 辐射供暖系统
_\*2599676 汽车工程 自动变速器 自动控制系统 换挡智能化 换挡控制器
_\*2599677 船舶 强度 直接计算板
_\*2599678 微柱高效液相色谱法 测定 茶多酚 茶叶
_\*2599679 出版单位 出版体制改革 现代企业制度 国有资产管理
_\*2599680 车间作业调度 遗传算法 领域搜索 收敛性 稳定性

However ,   when I loaded the trained model using model.load(...) and model["_*0"] as tutorial did, I got exception of "Word not in vocabulary"

Finally I found there are no document vector in the model file. there are only word vectors.

pls help. thanks

**Comment by hiyijian** [comment]
I think I am aware the problem.

min-count MUST equals to 1, otherwise the doc id will be remove from vocab.

**Comment by danielfrg** [comment]
Thanks for reporting and solving this. I am closing since it looks solved to me.
