### ISSUE TITLE
How to setup word2phrase for n-grams (n > 2)?

### ISSUE THREAD

**Issue by amirj** [danielfrg/word2vec#22]
It seems that the word2phrase extract all unigram and bigram. I'm interested to n-grams (n>2). Is it possible to config it?

**Comment by danielfrg** [comment]
I don't think this is possible with in the current C code. The idea is to merge (2) words that together represent something like "Los Angeles" I am sure there is an example with 3 or more words but i cannot think of one right now so i am not sure how useful that will be.

In any case you might have more luck in the mailing list and if that is supported i'll add it: https://groups.google.com/forum/#!forum/word2vec-toolkit

**Comment by AssKicker0214** [comment]
For example, "New York City". Can I run word2phrase twice to achieve 3-gram?
