### ISSUE TITLE
 a question

### ISSUE THREAD

**Issue by angelteers** [danielfrg/word2vec#26]
hi,I want to ask a question about word2vec details. I read codes,the row of the vector matrix sorted by counting. Are words corresponding column vector the words corresponding row vector?If not ,how do you get the words corresponding row vector? thank you.

**Comment by danielfrg** [comment]
I am afraid i do not understand the question. Words are represented by the row vectors.

Take a look at the example notebook: http://nbviewer.ipython.org/github/danielfrg/word2vec/blob/master/examples/word2vec.ipynb

`model[word]` will give you the corresponding row vector.

To get a word from a vector you need the exact row vector which would be weird, you probably want to get the closest word to a vector using something like the cosine similarity, take a look at: https://github.com/danielfrg/word2vec/blob/master/word2vec/wordvectors.py#L57

**Comment by angelteers** [comment]
thank you .
