### ISSUE TITLE
word2vec.word2phrase() problem in python 3

### ISSUE THREAD

**Issue by ahmetax** [danielfrg/word2vec#37]
Hello,
I am using a Turkish dataset. (https://github.com/ahmetax/derlemtr/blob/master/buyuk_veri/hurriyet_noktasiz_2010_01.txt.rar)

word2vec.word2phrase(train=fin, output=fout, verbose=True) call immediately returns without making any thing, and without errors.
The problem might be related to special Turkish characters (utf-8).
I am using Python 3.5.1 on Ubuntu 16.04
word2vec.word2clusters() and word2vec.word2vec() run with no problems.
How can we solve that problem? (I can create phrase file by using a revised version of word2phrase.py from https://github.com/travisbrady/word2phrase )
Thank you.

Note: There is no problem when I use text8.

**Comment by ak-kat** [comment]
Similar issue with mine. I am executing the code:
http://nbviewer.jupyter.org/github/danielfrg/word2vec/blob/master/examples/word2vec.ipynb and using text8

word2vec.word2vec() and word2vec.word2clusters() working fine, but word2vec.word2phrase() not working.
Please tell me the solution as you have said that it is working fine for text8.

**Comment by Acecai** [comment]
verbose=False

**Comment by someAdjectiveNoun** [comment]
@ahmetax Did you identify some workaround or solution to this issue? I am trying to solve this same issue.
