### ISSUE TITLE
Wrong documentation about word2vec training

### ISSUE THREAD

**Issue by andreacimino** [danielfrg/word2vec#39]
In the provided docstrings (scripts_interface.py) the following is wrong:

> def word2vec(train, output, size=100, window=5, sample='1e-3', hs=0,
>              negative=5, threads=12, iter_=5, min_count=5, alpha=0.025,
>              debug=2, binary=1, cbow=1, save_vocab=None, read_vocab=None,
>              verbose=False):
> 
>    cbow <int>
>             Use the continuous back of words model; default is 1 (skip-gram
>             model)

When you run the word2vec program standalone you get this:

> WORD VECTOR estimation toolkit v 0.1c
> 
> Options:
> Parameters for training:
> [...]
>     -cbow <int>  
>                 Use the continuous bag of words model; default is 1 (use 0 for skip-gram model) 
> [...]

So the provided docstring should be changed to:

Use the continuous back of words model; default is 1 (cbow model)

**Comment by danielfrg** [comment]
Fixed at #48
