### ISSUE TITLE
Decoding error

### ISSUE THREAD

**Issue by nazandr** [danielfrg/word2vec#40]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/andrey/keras/lib/python3.6/site-packages/word2vec/io.py", line 18, in load
    return word2vec.WordVectors.from_binary(fname, *args, **kwargs)
  File "/Users/andrey/keras/lib/python3.6/site-packages/word2vec/wordvectors.py", line 171, in from_binary
    vocab[i] = word.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 64: unexpected end of data

```

**Comment by mrmattwright** [comment]
Ok this is to do with encoding....unfortunately the default training encodes binary files as 'ISO-8859-1' vs UTF-8. 

This is a bit annoying because if you use code like this and train your own model: 

```
 word2vec.word2vec('normalised_phrases2.txt',
                      temp_vec,
                      size=500)
```

then try and load it like this

```
model = word2vec.load(vector_file)
```

You'll get the error above. There is an answer though...which is to change the way you load a model to this: 

```
model = word2vec.WordVectors.from_binary(vector_file,encoding="ISO-8859-1")
```

The default for when you do `word2vec.load` and kind="bin" should probably be changed so this is the default behaviour.

**Comment by nazandr** [comment]
Model loads, but vocabulary looks like this
```
model.vocab
array(['Ð³Ð¾Ð´', '\x8dÑ\x82Ð¾', '\x80Ð¾Ñ\x81Ñ\x81Ð¸Ñ\x8f', ...,
       '¼Ð¾Ñ\x81ÐºÐ°Ð»Ñ\x8cÐºÐ¾Ð²Ð°', '½Ñ\x96Ñ\x82Ñ\x80Ð°Ñ\x82Ñ\x96Ð²',
       '¿ÐµÑ\x82Ñ\x80Ð¾Ð¿Ð°Ð²Ð»Ð¾Ð²ÐµÑ\x86'], 
      dtype='<U78')

```

**Comment by dranorter** [comment]
Just wanted to note that using "ISO-8859-1" worked for me, on this exact error. What data are you using, nazandr?

**Comment by hisen630** [comment]
@nazandr i come to the same problem.
what i notice is, in the unicode they are actually byte, like **"u'\xe5\x85\xac\xe5\x8f\xb8'"**
So, what i've done is to make a new dict like this:
```Python
new_vec = {}
for w in model.vocab:
    new_vec[("".join(map(chr,map(ord, a)))).decode('utf-8')] = model[w]
```
any access to the model should via this `new_vec`, and this works well for me, hope it helps.

**Comment by adelabdelli** [comment]
@hisen630 i got this error when i tried your code 
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-14-04785e6caf84> in <module>()
      1 new_vec = {}
      2 for w in model.vocab:
----> 3     new_vec[("".join(map(chr,map(ord, a)))).decode('utf-8')] = model[w]

NameError: name 'a' is not defined
```
what is 'a' variable ?

**Comment by hisen630** [comment]
@adelabdelli 
it should be 'w'. Try it out, the idea is just to convert the encoding, nothing more.
