### ISSUE TITLE
Multi language support

### ISSUE THREAD

**Issue by amr1tv1rd1** [danielfrg/word2vec#42]
Can it be used for languages other than English like Italian, Chinese, Spanish. ?

**Comment by danielfrg** [comment]
Yes in theory it should work if you train it with a dataset of than language. I have tested it a little bit in Spanish and it works. I don't know about Chinese since the language is so different.

**Comment by amr1tv1rd1** [comment]
Thanks @danielfrg , will test it with Chinese and then will see how does it go
