### ISSUE TITLE
install in Docker Container (ubuntu:16.10)

### ISSUE THREAD

**Issue by yesseecity** [danielfrg/word2vec#43]
In my docker container ubuntu:16.10

I well install this
`pip install word2vec`

But, I got error
`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-lczJ96/word2vec/`

I must install "Cython" to fixed it.
`pip install Cython`

--------------------

python version: 2.7
pip version:  9.0.1 (for python 2.7)

**Comment by danielfrg** [comment]
Ah yes, there is a small error on the `setup.py` that requires cython to be installed.

**Comment by danielfrg** [comment]
Documented the dependency now.
