### ISSUE TITLE
AttributeError: module 'word2vec' has no attribute 'word2vec'

### ISSUE THREAD

**Issue by gallupliu** [danielfrg/word2vec#44]
I ran into a problem “AttributeError: module 'word2vec' has no attribute 'word2vec'”

anaconda 4.3 on Centos 7

how to solve it？thanks

```
>>> import word2vec
>>> word2vec.word2vec('chatCorpus.txt', 'corpusWord2Vec.bin', size=50,verbose=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'word2vec' has no attribute 'word2vec'
```

**Comment by furas** [comment]
Maybe you created file `word2vec.py` 
and now `import word2vec` imports your file instead of module `word2vec`.
