### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 96-97: unexpected end of data

### ISSUE THREAD

**Issue by MingleiLI** [danielfrg/word2vec#58]
There is no problem when I train the model using:
`word2vec.word2vec(input_corpus_f, output_w2v_f, size=200, verbose=True, min_count = 5, binary=True)`

However, when I load the model using:
`model = word2vec.load(output_w2v_f)`
The above error occurs.

**Comment by jplehmann** [comment]
This worked for me:

https://github.com/danielfrg/word2vec/issues/54#issuecomment-418467398

**Comment by jplehmann** [comment]
Actually, on further investigation, that did NOT work verbatim.  I had to add the `new_lines` arg or it chopped the first char off every word:

```python
model = word2vec.load('GoogleNews-vectors-negative300.bin', encoding="ISO-8859-1", new_lines=False)
```

**Comment by danielfrg** [comment]
Thanks for the comment John. Depending on the training parameters those flags might be needed.
