### ISSUE TITLE
While installing the word2Vec library getting the following errors.

### ISSUE THREAD

**Issue by manojrustagi79** [danielfrg/word2vec#67]
ERROR: Command errored out with exit status 1:
   command: 'D:\Anaconda\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\manoj\\AppData\\Local\\Temp\\pip-install-0w9h1x7a\\word2vec\\setup.py'"'"'; __file__='"'"'C:\\Users\\manoj\\AppData\\Local\\Temp\\pip-install-0w9h1x7a\\word2vec\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\manoj\AppData\Local\Temp\pip-wheel-oiecgwem'
       cwd: C:\Users\manoj\AppData\Local\Temp\pip-install-0w9h1x7a\word2vec\
  Complete output (33 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\word2vec
  copying word2vec\io.py -> build\lib.win-amd64-3.7\word2vec
  copying word2vec\scripts_interface.py -> build\lib.win-amd64-3.7\word2vec
  copying word2vec\utils.py -> build\lib.win-amd64-3.7\word2vec
  copying word2vec\wordclusters.py -> build\lib.win-amd64-3.7\word2vec
  copying word2vec\wordvectors.py -> build\lib.win-amd64-3.7\word2vec
  copying word2vec\_version.py -> build\lib.win-amd64-3.7\word2vec
  copying word2vec\__init__.py -> build\lib.win-amd64-3.7\word2vec
  creating build\lib.win-amd64-3.7\word2vec\tests
  copying word2vec\tests\test_word2vec.py -> build\lib.win-amd64-3.7\word2vec\tests
  copying word2vec\tests\__init__.py -> build\lib.win-amd64-3.7\word2vec\tests
  UPDATING build\lib.win-amd64-3.7\word2vec/_version.py
  set build\lib.win-amd64-3.7\word2vec/_version.py to '0.10.6'
  running build_ext
  building 'word2vec.word2vec_noop' extension
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  creating build\temp.win-amd64-3.7\Release\word2vec
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -ID:\Anaconda\include -ID:\Anaconda\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcword2vec/word2vec_noop.c /Fobuild\temp.win-amd64-3.7\Release\word2vec/word2vec_noop.obj  word2vec_noop.c
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:D:\Anaconda\libs /LIBPATH:D:\Anaconda\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64" /EXPORT:PyInit_word2vec_noop build\temp.win-amd64-3.7\Release\word2vec/word2vec_noop.obj /OUT:build\lib.win-amd64-3.7\word2vec\word2vec_noop.cp37-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.7\Release\word2vec\word2vec_noop.cp37-win_amd64.lib
     Creating library build\temp.win-amd64-3.7\Release\word2vec\word2vec_noop.cp37-win_amd64.lib and object build\temp.win-amd64-3.7\Release\word2vec\word2vec_noop.cp37-win_amd64.exp
  Generating code
  Finished generating code
  installing to build\bdist.win-amd64\wheel
  running install
  error: [WinError 2] The system cannot find the file specified
  Compilation command: gcc C:\Users\manoj\AppData\Local\Temp\pip-install-0w9h1x7a\word2vec\word2vec\src\win32/word2vec.c -o Scripts\word2vec.exe -O2 -Wall -funroll-loops
  ----------------------------------------
  ERROR: Failed building wheel for word2vec
  Running setup.py clean for word2vec
Failed to build word2vec
Installing collected packages: word2vec
    Running setup.py install for word2vec ... error
    ERROR: Command errored out with exit status 1:
     command: 'D:\Anaconda\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\manoj\\AppData\\Local\\Temp\\pip-install-0w9h1x7a\\word2vec\\setup.py'"'"'; __file__='"'"'C:\\Users\\manoj\\AppData\\Local\\Temp\\pip-install-0w9h1x7a\\word2vec\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\manoj\AppData\Local\Temp\pip-record-skgqfgah\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\Anaconda\Include\word2vec'
         cwd: C:\Users\manoj\AppData\Local\Temp\pip-install-0w9h1x7a\word2vec\
    Complete output (3 lines):
    running install
    error: [WinError 2] The system cannot find the file specified
    Compilation command: gcc C:\Users\manoj\AppData\Local\Temp\pip-install-0w9h1x7a\word2vec\word2vec\src\win32/word2vec.c -o Scripts\word2vec.exe -O2 -Wall -funroll-loops
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'D:\Anaconda\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\manoj\\AppData\\Local\\Temp\\pip-install-0w9h1x7a\\word2vec\\setup.py'"'"'; __file__='"'"'C:\\Users\\manoj\\AppData\\Local\\Temp\\pip-install-0w9h1x7a\\word2vec\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\manoj\AppData\Local\Temp\pip-record-skgqfgah\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\Anaconda\Include\word2vec' Check the logs for full command output.
(base) PS C:\windows\system32>

**Comment by danielfrg** [comment]
Windows is not very supported by this packages.
Try one of the new releases and see if it fixes it but I dont think so.
For a python native version look at gensim implementation of word2vec.
