### ISSUE TITLE
How can I use google's word2vec?

### ISSUE THREAD

**Issue by orko19** [danielfrg/word2vec#73]
I want to use your interface but with google's pre-trained word2vec, instead of the sample data .
So instead of:
`model = word2vec.load('../data/text8.bin')
`it will be:
`model = word2vec.load('word2vec-google-news-300')
`
Is that possible?

**Comment by danielfrg** [comment]
Yes, thats totally possible, just point it to the right path.

**Comment by orko19** [comment]
@danielfrg What is the path?
